export const MOCK_EVENTS = [
  {
    id: 'evt_001',
    sport: '⚽',
    sportName: 'Football',
    competition: 'Premier League',
    home: 'Chelsea',
    away: 'Arsenal',
    startTime: new Date(Date.now() + 3600000 * 2).toISOString(),
    oddHome: 2.10,
    oddDraw: 3.40,
    oddAway: 3.20,
    kairosScore: 88,
    riskLevel: 'Faible',
    confidence: 91,
    probability: 74,
    dataQuality: 'Excellente',
    breakdown: [
      { label: 'Forme récente excellente', value: +15, good: true },
      { label: 'Motivation élevée', value: +12, good: true },
      { label: 'Blessures adverses (2)', value: +8, good: true },
      { label: 'Smart Money favorable', value: +10, good: true },
      { label: 'Fatigue adverse', value: +7, good: true },
      { label: 'Risque de nul', value: -6, good: false },
      { label: 'Données incomplètes', value: -3, good: false },
    ],
    smartMoney: { smallBettorsPct: 60, bigMoneyPct: 70, alert: false, direction: 'Chelsea' },
    recommendation: 'parier',
  },
  {
    id: 'evt_002',
    sport: '🎾',
    sportName: 'Tennis',
    competition: 'Roland Garros — QF',
    home: 'Djokovic',
    away: 'Alcaraz',
    startTime: new Date(Date.now() + 3600000 * 5).toISOString(),
    oddHome: 1.70,
    oddDraw: null,
    oddAway: 2.10,
    kairosScore: 83,
    riskLevel: 'Moyen',
    confidence: 78,
    probability: 67,
    dataQuality: 'Bonne',
    breakdown: [
      { label: 'Forme récente favorable', value: +14, good: true },
      { label: 'Surface favorable (terre)', value: +10, good: true },
      { label: 'H2H favorable', value: +8, good: true },
      { label: 'Fatigue adverse', value: +5, good: true },
      { label: 'Fatigue propre', value: -6, good: false },
      { label: 'Pression médiatique', value: -5, good: false },
    ],
    smartMoney: { smallBettorsPct: 55, bigMoneyPct: 65, alert: false, direction: 'Djokovic' },
    recommendation: 'surveiller',
  },
  {
    id: 'evt_003',
    sport: '🏀',
    sportName: 'Basketball',
    competition: 'NBA Playoffs',
    home: 'Boston Celtics',
    away: 'Cleveland Cavaliers',
    startTime: new Date(Date.now() + 3600000 * 8).toISOString(),
    oddHome: 1.55,
    oddDraw: null,
    oddAway: 2.40,
    kairosScore: 91,
    riskLevel: 'Faible',
    confidence: 94,
    probability: 79,
    dataQuality: 'Excellente',
    breakdown: [
      { label: 'Forme récente excellente', value: +18, good: true },
      { label: 'Motivation (playoffs)', value: +15, good: true },
      { label: 'Blessures adverses (3)', value: +12, good: true },
      { label: 'Smart Money favorable', value: +10, good: true },
      { label: 'H2H favorable', value: +7, good: true },
      { label: 'Données incomplètes', value: -4, good: false },
    ],
    smartMoney: { smallBettorsPct: 45, bigMoneyPct: 75, alert: true, alertMsg: 'Mouvement inhabituel — gros argent vers Celtics (75%) malgré seulement 45% petits parieurs', direction: 'Boston Celtics' },
    recommendation: 'parier',
  },
  {
    id: 'evt_004',
    sport: '🏉',
    sportName: 'Rugby',
    competition: 'Top 14',
    home: 'Stade Toulousain',
    away: 'Stade Rochelais',
    startTime: new Date(Date.now() + 3600000 * 24).toISOString(),
    oddHome: 1.80,
    oddDraw: 12.00,
    oddAway: 2.00,
    kairosScore: 76,
    riskLevel: 'Moyen',
    confidence: 72,
    probability: 63,
    dataQuality: 'Bonne',
    breakdown: [
      { label: 'Forme récente favorable', value: +10, good: true },
      { label: 'Motivation (finale)', value: +12, good: true },
      { label: 'Fatigue adverse', value: +6, good: true },
      { label: 'Blessures propres (1)', value: -4, good: false },
      { label: 'Risque déplacement', value: -5, good: false },
    ],
    smartMoney: { smallBettorsPct: 50, bigMoneyPct: 55, alert: false, direction: 'Stade Toulousain' },
    recommendation: 'surveiller',
  },
];

export const MOCK_STATS = {
  totalAnalyzed: 14872,
  premiumCount: 3,
  ignoredCount: 11248,
  lastUpdated: new Date().toISOString(),
};

export const MOCK_USER_STATS = {
  totalBets: 47,
  wins: 27,
  losses: 20,
  winRate: 57.4,
  roi: 12.3,
  bestSport: 'Football',
  bestOddRange: '1.20 – 1.60',
  bestTicketSize: '3 à 5 matchs',
  worstSport: 'MMA',
  worstROI: -34,
  recentBets: [
    { id: 1, ticket: 'Chelsea + Celtics', stake: 100, result: 'win', gain: 155, date: '2026-06-01' },
    { id: 2, ticket: 'Djokovic + PSG + Lyon', stake: 50, result: 'loss', gain: 0, date: '2026-05-30' },
    { id: 3, ticket: 'Real Madrid', stake: 200, result: 'win', gain: 280, date: '2026-05-28' },
  ],
};
